POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Test Product",
  "price": 1499.99
}

###
GET http://localhost:8080/products
Content-Type: application/json

###
GET http://localhost:8080/products/beae5a0e-1873-4ca6-9f3f-7b351c56c6bd

###
PUT http://localhost:8080/products/beae5a0e-1873-4ca6-9f3f-7b351c56c6bd
Content-Type: application/json

{
  "name": "Updated Product",
  "price": 1999.99
}

###
DELETE http://localhost:8080/products/beae5a0e-1873-4ca6-9f3f-7b351c56c6bd
Content-Type: application/json
